project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Assignment1.qmd

format:
  html:
    theme: minty
    mainfont: Georgia, serif;
    css: styles.css
    toc: true

editor: visual

