project:
  type: website
  output-dir: docs

website:
  title: "Momo's Website"
  navbar:
    left:
  
      - href: index.qmd
        text: Home
      - text: Group Project
        menu:
          - href: Proposal.qmd
            text: Proposal
          - href: EPPS6356_Presentation.pdf  
            text: Final Project Presentation
          - href: finalproject.html
            text: Final Project
      - text: Assignments
        menu:
        - href: Assignment1.qmd
          text: Assignment1
        - href: Assignment2.qmd
          text: Assignment2
        - href: Assignment3.qmd
          text: Assignment3
        - href: Assignment4.qmd
          text: Assignment4
        - href: Assignment5.qmd
          text: Assignment5
        - href: Assignment6.qmd
          text: Assignment6
        - href: Assignment7.qmd
          text: Assignment7
        - href: Assignment8.qmd
          text: Assignment8
        - href: Assignment9.qmd
          text: Assignment9
        - href: Assignment10.qmd
          text: Assignment10
      
format:
  html:
    theme: minty
    mainfont: Georgia, serif
    css: styles.css
    toc: true

editor: visual



