project:
  type: website
  output-dir: docs

website:
  title: "Momo's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Assignment1.qmd
      - Assignment2.qmd
      - Assignment3.qmd
      - Assignment4.qmd
      - Assignment5.qmd
      - Assignment6.qmd
      

format:
  html:
    theme: minty
    mainfont: Georgia, serif;
    css: styles.css
    toc: true

editor: visual

