---
title: "Assignment 2"
---

```{r}
#Q1
## Paul Murrell's R examples (selected)

## Start plotting from basics 
# Note the order
plot(pressure, pch=14)  # Can you change pch?
#Changed from 16 to 14
text(150, 600, 
     "Pressure (mm Hg)\nversus\nTemperature (Celsius)")

#  Examples of standard high-level plots 
#  In each case, extra output is also added using low-level 
#  plotting functions.
# 

# Setting the parameter (3 rows by 2 cols)
par(mfrow=c(3, 2))

# Scatterplot
# Note the incremental additions

x <- c(0.5, 2, 4, 8, 12, 16)
y1 <- c(1, 1.3, 1.9, 3.4, 3.9, 4.8)
y2 <- c(4, .8, .5, .45, .4, .3)

# Setting label orientation, margins c(bottom, left, top, right) & text size
par(las=1, mar=c(4, 4, 2, 4), cex=.7) 
plot.new()
plot.window(range(x), c(0, 6))
lines(x, y1)
lines(x, y2)
points(x, y1, pch=16, cex=2) # Try different cex value?  
points(x, y2, pch=21, bg="wheat", cex=2)  # Different background color - changed from white to wheat
par(col="gray50", fg="gray50", col.axis="gray50")
axis(1, at=seq(0, 16, 4)) # What is the first number standing for?
#1 stands for the x-axis
axis(2, at=seq(0, 6, 2))
axis(4, at=seq(0, 6, 2))
box(bty="u")
mtext("Travel Time (s)", side=1, line=2, cex=0.8)
mtext("Responses per Travel", side=2, line=2, las=0, cex=0.8)
mtext("Responses per Second", side=4, line=2, las=0, cex=0.8)
text(4, 5, "Bird 131")
par(mar=c(5.1, 4.1, 4.1, 2.1), col="black", fg="black", col.axis="black")

# Histogram
# Random data
Y <- rnorm(50)
# Make sure no Y exceed [-3.5, 3.5]
Y[Y < -3.5 | Y > 3.5] <- NA # Selection/set range
x <- seq(-3.5, 3.5, .1)
dn <- dnorm(x)
par(mar=c(4.5, 4.1, 3.1, 0))
hist(Y, breaks=seq(-3.5, 3.5), ylim=c(0, 0.5), 
     col="gray80", freq=FALSE)
lines(x, dnorm(x), lwd=2)
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Barplot
par(mar=c(2, 3.1, 2, 2.1)) 
midpts <- barplot(VADeaths, 
                  col=gray(0.1 + seq(1, 9, 2)/11), 
                  names=rep("", 4))
mtext(sub(" ", "\n", colnames(VADeaths)),
      at=midpts, side=1, line=0.5, cex=0.5)
text(rep(midpts, each=5), apply(VADeaths, 2, cumsum) - VADeaths/2,
     VADeaths, 
     col=rep(c("white", "black"), times=3:2), 
     cex=0.8)
par(mar=c(5.1, 4.1, 4.1, 2.1))  

# Boxplot
par(mar=c(3, 4.1, 2, 0))
boxplot(len ~ dose, data = ToothGrowth,
        boxwex = 0.25, at = 1:3 - 0.2,
        subset= supp == "VC", col="white",
        xlab="",
        ylab="tooth length", ylim=c(0,35))
mtext("Vitamin C dose (mg)", side=1, line=2.5, cex=0.8)
boxplot(len ~ dose, data = ToothGrowth, add = TRUE,
        boxwex = 0.25, at = 1:3 + 0.2,
        
        subset= supp == "OJ")
legend(1.5, 9, c("Ascorbic acid", "Orange juice"), 
       fill = c("white", "gray"), 
       bty="n")
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Persp
x <- seq(-10, 10, length= 30)
y <- x
f <- function(x,y) { r <- sqrt(x^2+y^2); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
# 0.5 to include z axis label
par(mar=c(0, 0.5, 0, 0), lwd=0.5)
persp(x, y, z, theta = 30, phi = 30, 
      expand = 0.5)
par(mar=c(5.1, 4.1, 4.1, 2.1), lwd=1)

# Piechart
par(mar=c(0, 2, 1, 2), xpd=FALSE, cex=0.5)
pie.sales <- c(0.12, 0.3, 0.26, 0.16, 0.04, 0.12)
names(pie.sales) <- c("Blueberry", "Cherry",
                      "Apple", "Boston Cream", "Other", "Vanilla")
pie(pie.sales, col = gray(seq(0.3,1.0,length=6))) 

# Exercise: Can you generate these charts individually?  Try these functions 
# using another dataset. Be sure to work on the layout and margins

```

```{r}
library(readr)
hpi <- read_csv("hpi3.csv") #import the csv file
spec(hpi)
summary(hpi)
head(hpi)

lifeexpec <- hpindex$`LIFE EXPECTANCY`
hpi <- hpindex$HPI
gdp <- hpindex$`GDP PER CAPITA`
webg <- hpindex$`WELL BEING`
ecofoot <- hpindex$`ECOLOGICAL FOOTPRINT`
cont <- hpindex$CONTINENT

# Scatterplot
plot(lifeexpec, hpi, pch=21)
title("Scatterplot: Life Expectancy vs. HPI")
xlabel <- "Life Expectancy"
ylabel <- "Happy Planet Index"
text(mean(lifeexpec), max(hpi), labels = c(xlabel, ylabel), pos = 0.5)


```

```{r}
#install.packages("scatterplot3d")
# 3D Scatterplot
library("scatterplot3d")
s3d <- scatterplot3d(lifeexpec, gdp, hpi, color="indianred4", pch=16, main="3D Scatterplot")
s3d$plane3d(s3d$xyz.convert(mean(lifeexpec), mean(gdp), mean(hpi)))

```

```{r}
# Barplot
barplot(table(cont), main="Barplot of Continents", xlab="Continent", ylab="Frequency", col="lightpink1", )

# Add a legend
legend("topleft", 
       legend = c("1 = South America", "2 = USA,CAN,AUS,NZ", "3 = Europe", "4 = ME Asia", "5 = Africa", "6 = South Asia", "7 = Eurasia", "8 = East Asia"), 
       title = "Legend", cex = 0.45)




```

```{r}
######HISTOGRAM######
par(mfrow=c(1,1))
par(mar=c(4.5, 4.1, 3.1, 4), xaxs = "i", yaxs = "i")
#hpidensity <- density(hpi)
hist(hpi,
     xlab= 'Happiness Index', ylab = 'Density',
     breaks=seq(0, 100), ylim=c(0, 10), 
     col="turquoise", freq=TRUE)
#mx <- hpif
```

```{r}
slices <- c(84.9, 84.6, 83.6, 83.5, 83.8)
lbls <- c("HongKong", "Japan", "Singapore", "Italy", "Switzerland")
pct <- round(slices)
lbls <- paste(lbls, pct)
lbls <- paste(lbls, "%", sep = "")

# Define custom colors for each slice
custom_colors <- c("firebrick", "darkseagreen", "skyblue", "plum2", "coral")

# Create the pie chart with custom colors
pie(slices, labels = lbls, col = custom_colors,
    main = "Top 5 Countries with the highest life expectancy")


```

```{r}
# Sample data

x <- c(1433783.7, 1366417.8, 329064.9, 270625.6, 216565.3, 211049.5, 200963.6, 163046.2, 145872.3, 127575.5)

y <- c(42, 36, 37, 50, 45, 54, 34, 54, 35, 54)

# Create a blank plot
plot(x, y, type = "n", xlab = "Population", ylab = "HPI", main = "HPI vs Populations (Most populated)")

# Add points
points(round(x), y, pch = 16, col = "blue", cex = 1)

# Add a box around the plot
box()

# Add text labels
text(x, y, labels = c("China", "India", "USA", "Indonesia", "Pakistan", "Brazil", "Nigeria", "Bangladesh", "Russia", "Mexico"), pos = 3, col = "black")

# Add axis labels
axis(1, at = x, labels = x, col = "black")
axis(2, at = y, labels = y, col = "black")



```
